TableGroup QuickTasks [color: #1E69FD] {
  QuickCollection
  QuickTask
}

Table QuickCollection {
  id int pk
  userUuid uuid [ref: > User.uuid]
  name string
}
Table QuickTask {
  id int pk
  userUuid uuid [ref: > User.uuid]
  label string
  createdAt datetime
  completedAt datetime [null]
}
